modLoader="javafml"
loaderVersion="${loader_version_range}" 

license="${mod_license}"

[[mods]]
modId="chef_craft"
version="${mod_version}" 
displayName="${mod_name}" 
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.chef_craft]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
